name: APIsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_APIsec_scan:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: APIsec scan
        uses: apisec-inc/apisec-run-scan@025432089674a28ba8fb55f8ab06c10215e772ea
        with:
          # Correct parameter names:
          username: ${{ secrets.APISEC_USERNAME }}
          password: ${{ secrets.APISEC_PASSWORD }}
          # Project details:
          project: "VAmPI"
          profile: "Master"
          # Output file:
          outputfile: "apisec-results.sarif"
          
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: apisec-results.sarif
