name: APIsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_APIsec_scan:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: APIsec scan
        uses: apisec-inc/apisec-run-scan@025432089674a28ba8fb55f8ab06c10215e772ea
        with:
          # Correct parameter names as per the action's specification
          apisec-username: ${{ secrets.APISEC_USERNAME }}
          apisec-password: ${{ secrets.APISEC_PASSWORD }}
          apisec-project: "VAmPI"
          apisec-profile: "Master"
          sarif-result-file: "apisec-results.sarif"
          
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: apisec-results.sarif
